---
title: "Big Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r big_read, cache = TRUE}
# The real data does not have the same columns as the demo data. Very annoying!
# Note you can use the n_max argument to read_csv() to just read in the first
# 100 or so rows, thereby quickly getting back the message about the column
# types. Then, we use this new listing of types. Use cache = TRUE so that you
# don't have to repeat long calculations every time you reknit the document.

x <- read_csv("~/data/census/censoc_dmf_v2/censoc_dmf_v2.csv",
                   col_types = cols(HISTID = col_character(),
                                    byear = col_double(),
                                    bmonth = col_double(),
                                    dyear = col_double(),
                                    dmonth = col_double(),
                                    death_age = col_double(),
                                    link_abe_exact_conservative = col_double(),
                                    weight = col_double(),
                                    weight_conservative = col_double()))
```


create a 1% sample 
plot of dmonth 


```{r}
# all questions begin with a tibble: which tibble? For sample_frac(), could also use slice_sample(prop = .01)
# working with big data: get the data, take a little sample and get everything working, then sub in the big data

small <- x %>% 
  sample_frac(1/100) 
 
```

```{r}

# to go from data to a given plot, one tactic is to pick one point, and disect what's needed to get that one point (or place on the plot)
# revisit summarize 

x %>%
  filter(dmonth %in% c(1, 7)) %>%
  select(dmonth, dyear) %>%
  group_by(dyear, dmonth) %>%
  summarize(deaths = n()) %>%
  pivot_wider(names_from = dmonth, 
              values_from = deaths) %>%
  rename(jan = "1", july = "7") %>%
  mutate(ratio = jan/july) %>%
  
  ggplot(mapping = aes(x = , dyear, 
                       y = ratio)) +
  geom_point() +
  geom_smooth(method = 'lm', 
              formula = 'y ~ x') +
  labs(title = "Mortality over Time",
       subtitle = "Why are Januaries becoming more dangerous?",
       y = "Ratio of January to July Deaths",
       x = "Year of Death",
       caption = "Source: CenSoc")

```


